server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: projects
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/projects/**
        - id: employees
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/employees/**

